config/routes.rb
Rails.application.routes.draw do
root 'static_pages#home'
get '/contact-us',to: 'static_pages#contact'
get '/about-us', to: 'static_pages#about'
get '/hello-world', to: 'static_pages#helloworld'
get '/about-me', to: 'static_pages#aboutme'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def helloworld
  end

  def aboutme
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar fixed-bottom navbar-light bg-faded">
  <a class="navbar-brand" href="#">I LOVE BACON</a>
      <h3>Company<span>logo</span></h3>

      <p class="footer-links">
        <a href="#">Home</a>
        ·
        <a href="#">Blog</a>
        ·
        <a href="#">Pricing</a>
        ·
        <a href="#">About</a>
        ·
        <a href="#">Faq</a>
        ·
        <a href="#">Contact</a>
      </p>

      <p class="footer-company-name">Company Name &copy; 2015</p>

      <div class="footer-icons">

        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-linkedin"></i></a>
        <a href="#"><i class="fa fa-github"></i></a>

      </div>
    </nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Navbar</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/hello-world">helloworld<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/about-us">About</a>
      </li>
      <li class="nav-item">
          <%= link_to "About Me" , about_me_path, {:class => "nav-link"} %>
      </li>
      <li class="nav-item">
            <%= link_to "Contact Us" , contact_us_path, {:class => "nav-link"} %>
      </li>
      <li class="nav-item">
      <%= link_to "Homepage" , root_path, {:class => "nav-link"} %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/footer' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/aboutme.html.erb
<div class="mybuttononmypage">
<button><%= link_to "Homepage" , root_path, {:class => "nav-link"} %></button>
</div>

app/views/static_pages/contact.html.erb
<div class="container main">
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>
</div>

app/views/static_pages/helloworld.html.erb
<h1>StaticPages#hello_world</h1>
<p>Find me in app/views/static_pages/hello_world.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>